ALTER TABLE "Department" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "SystemSetting" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
