import { AlertTriangle, ArrowDownRight, ArrowUpRight, Building2, CalendarDays, CheckCircle2, ChevronRight, CircleAlert, Clock3, Plus, Target, TrendingUp, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { Spinner } from '../components/UI';
import { statusMeta } from '../types';

export default function Dashboard(){const [data,setData]=useState<any>();const [year,setYear]=useState(2026);useEffect(()=>{api(`/dashboard?year=${year}`).then(setData)},[year]);if(!data)return <Spinner/>;
 const cards=[
  {label:'Tổng chỉ tiêu',value:data.total,meta:`Kế hoạch năm ${year}`,icon:Target,tone:'teal',trend:'+6',up:true},
  {label:'Đã hoàn thành',value:data.counts.COMPLETED||0,meta:`${data.total?Math.round((data.counts.COMPLETED||0)/data.total*100):0}% tổng chỉ tiêu`,icon:CheckCircle2,tone:'blue',trend:'+3',up:true},
  {label:'Đúng tiến độ',value:data.counts.ON_TRACK||0,meta:'Đang được kiểm soát',icon:TrendingUp,tone:'green',trend:'+2',up:true},
  {label:'Cần tập trung',value:(data.counts.AT_RISK||0)+(data.counts.OVERDUE||0),meta:`${data.counts.OVERDUE||0} chỉ tiêu quá hạn`,icon:AlertTriangle,tone:'orange',trend:'-1',up:false},
 ];
 return <><div className="command-head"><div><span className="eyebrow">CONTROL ROOM · {year}</span><h2>Bức tranh điều hành hôm nay</h2><p>Tổng hợp tiến độ thực hiện chỉ tiêu từ các đơn vị trực thuộc.</p></div><div className="page-actions"><select value={year} onChange={e=>setYear(+e.target.value)}><option>2026</option><option>2025</option></select><Link className="btn primary" to="/admin/targets?new=1"><Plus/>Đặt chỉ tiêu</Link></div></div>
 <div className="overview-banner"><div><span>TIẾN ĐỘ CHUNG TOÀN PHƯỜNG</span><strong>{data.overallProgress}<small>%</small></strong><p>{data.overallProgress>=70?'Tiến độ đang bám sát kế hoạch năm':'Cần tăng tốc các chỉ tiêu trọng tâm'}</p></div><div className="ring" style={{'--p':`${data.overallProgress*3.6}deg`} as any}><span>{data.overallProgress}%</span></div><div className="banner-stats"><div><CheckCircle2/><span><b>{data.counts.COMPLETED||0}</b> hoàn thành</span></div><div><Clock3/><span><b>{data.counts.ON_TRACK||0}</b> đúng tiến độ</span></div><div><CircleAlert/><span><b>{(data.counts.AT_RISK||0)+(data.counts.OVERDUE||0)}</b> cần xử lý</span></div></div><div className="banner-date"><CalendarDays/><span>Dữ liệu cập nhật<br/><b>{new Date(data.updatedAt).toLocaleString('vi-VN')}</b></span></div></div>
 <div className="stat-grid">{cards.map(({label,value,meta,icon:Icon,tone,trend,up})=><div className="stat-card" key={label}><div className={`stat-icon ${tone}`}><Icon/></div><div className={`trend ${up?'up':'down'}`}>{up?<ArrowUpRight/>:<ArrowDownRight/>}{trend}</div><span>{label}</span><strong>{value}</strong><p>{meta}</p></div>)}</div>
 <div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><h3>Tiến độ theo phòng ban</h3><p>So sánh mức hoàn thành chỉ tiêu giữa các đơn vị</p></div><Link to="/admin/departments">Xem cơ cấu <ChevronRight/></Link></div><div className="department-progress">{data.departments.map((d:any)=><div className="dep-row" key={d.id}><div className="dep-symbol" style={{background:d.color+'18',color:d.color}}><Building2/></div><div className="dep-info"><div><strong>{d.name}</strong><span>{d.completed}/{d.total} hoàn thành</span></div><div className="progress"><i style={{width:`${d.progress}%`,background:d.color}}/></div></div><b>{d.progress}%</b></div>)}</div></section>
 <section className="panel alert-panel"><div className="panel-head"><div><h3>Cần chú ý</h3><p>Ưu tiên xử lý sớm</p></div><span className="alert-count">{data.alerts.length}</span></div><div className="alerts">{data.alerts.map((t:any)=><Link to="/admin/targets" key={t.id}><div className={`alert-dot ${t.status==='OVERDUE'?'danger':''}`}><AlertTriangle/></div><div><strong>{t.title}</strong><span>{t.department.name} · Hạn {new Date(t.dueDate).toLocaleDateString('vi-VN')}</span></div><ChevronRight/></Link>)}</div></section>
 <section className="panel span-2"><div className="panel-head"><div><h3>Nhịp cập nhật gần đây</h3><p>Dữ liệu mới nhất từ các đầu mối</p></div></div><div className="timeline">{data.recent.length?data.recent.map((x:any)=><div className="timeline-row" key={x.id}><div className="timeline-mark"/><div><strong>{x.target.code} · {x.target.title}</strong><span>{x.user.fullName} cập nhật <b>{x.value.toLocaleString('vi-VN')} {x.target.unit}</b></span></div><time>{new Date(x.createdAt).toLocaleDateString('vi-VN')}</time></div>):<p>Chưa có cập nhật mới.</p>}</div></section>
 <section className="panel"><div className="panel-head"><div><h3>Cơ cấu trạng thái</h3><p>{data.total} chỉ tiêu đang theo dõi</p></div></div><div className="status-stack"><div className="stack-bar">{Object.entries(data.counts).map(([key,count]:any)=><i key={key} className={statusMeta[key]?.color} style={{width:`${data.total?count/data.total*100:0}%`}} title={statusMeta[key]?.label}/>)}</div>{Object.entries(data.counts).map(([key,count]:any)=><div className="stack-label" key={key}><span><i className={statusMeta[key]?.color}/>{statusMeta[key]?.label}</span><b>{count}</b></div>)}</div></section></div></>}
