import { Calendar, ChevronLeft, ChevronRight, Filter, MoreHorizontal, Plus, Search, SlidersHorizontal, Target as TargetIcon, Upload, X } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../api';
import { Empty, Modal, PageHead, Spinner } from '../components/UI';
import type { Department, Target } from '../types'; import { statusMeta } from '../types';

const initial={code:'',title:'',description:'',unit:'%',targetValue:100,currentValue:0,weight:1,year:2026,frequency:'YEARLY',dueDate:'2026-12-31',departmentId:''};
export default function Targets(){const [targets,setTargets]=useState<Target[]>([]);const [deps,setDeps]=useState<Department[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [dep,setDep]=useState('');const [form,setForm]=useState<any>(initial);const [modal,setModal]=useState<'create'|'progress'|null>(null);const [selected,setSelected]=useState<Target|null>(null);const [progress,setProgress]=useState({value:0,note:''});const [error,setError]=useState('');const [params,setParams]=useSearchParams();
 const load=()=>{setLoading(true);Promise.all([api('/targets?year=2026'),api('/departments')]).then(([t,d])=>{setTargets(t);setDeps(d);if(!form.departmentId&&d[0])setForm((f:any)=>({...f,departmentId:d[0].id}))}).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[]);useEffect(()=>{if(params.get('new')==='1'){setModal('create');setParams({})}},[params]);
 const visible=useMemo(()=>targets.filter(t=>(!search||`${t.code} ${t.title}`.toLowerCase().includes(search.toLowerCase()))&&(!status||t.status===status)&&(!dep||t.department.id===dep)),[targets,search,status,dep]);
 async function create(e:FormEvent){e.preventDefault();setError('');try{await api('/targets',{method:'POST',body:JSON.stringify({...form,targetValue:+form.targetValue,currentValue:+form.currentValue,weight:+form.weight,year:+form.year})});setModal(null);setForm({...initial,departmentId:deps[0]?.id||''});load()}catch(e:any){setError(e.message)}}
 async function updateProgress(e:FormEvent){e.preventDefault();if(!selected)return;setError('');try{await api(`/targets/${selected.id}/progress`,{method:'POST',body:JSON.stringify({value:+progress.value,note:progress.note})});setModal(null);load()}catch(e:any){setError(e.message)}}
 function openProgress(t:Target){setSelected(t);setProgress({value:t.currentValue,note:''});setModal('progress')}
 return <><PageHead eyebrow="CHỈ TIÊU · KẾ HOẠCH 2026" title="Danh mục chỉ tiêu" description="Thiết lập, giao trách nhiệm và theo dõi tiến độ thực hiện trên một màn hình." actions={<><button className="btn secondary"><Upload/>Import Excel</button><button className="btn primary" onClick={()=>setModal('create')}><Plus/>Đặt chỉ tiêu</button></>}/>
 <div className="toolbar"><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm theo mã hoặc tên chỉ tiêu..."/>{search&&<button onClick={()=>setSearch('')}><X/></button>}</div><select value={dep} onChange={e=>setDep(e.target.value)}><option value="">Tất cả phòng ban</option>{deps.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(statusMeta).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select><button className="btn icon-only" title="Bộ lọc"><SlidersHorizontal/></button></div>
 <div className="table-card"><div className="table-summary"><span>Hiển thị <b>{visible.length}</b> / {targets.length} chỉ tiêu</span><button><Filter/> Lưu bộ lọc</button></div>{loading?<Spinner/>:visible.length?<div className="table-wrap"><table><thead><tr><th>Mã / Chỉ tiêu</th><th>Đơn vị phụ trách</th><th>Tiến độ</th><th>Hạn hoàn thành</th><th>Trạng thái</th><th/></tr></thead><tbody>{visible.map(t=>{const p=Math.min(Math.round(t.currentValue/Math.max(t.targetValue,.001)*100),100);return <tr key={t.id}><td><div className="target-cell"><div className="target-mini"><TargetIcon/></div><div><span>{t.code}</span><strong>{t.title}</strong></div></div></td><td><div className="department-cell"><i style={{background:t.department.color}}/>{t.department.name}</div></td><td><div className="progress-cell"><div><span>{t.currentValue.toLocaleString('vi-VN')} / {t.targetValue.toLocaleString('vi-VN')} {t.unit}</span><b>{p}%</b></div><div className="progress"><i className={p>=100?'done':''} style={{width:`${p}%`}}/></div></div></td><td><div className="date-cell"><Calendar/>{new Date(t.dueDate).toLocaleDateString('vi-VN')}</div></td><td><span className={`status ${statusMeta[t.status]?.color}`}><i/>{statusMeta[t.status]?.label}</span></td><td><button className="row-action" onClick={()=>openProgress(t)} title="Cập nhật tiến độ"><MoreHorizontal/></button></td></tr>})}</tbody></table></div>:<Empty title="Không tìm thấy chỉ tiêu" description="Thử thay đổi bộ lọc hoặc tạo một chỉ tiêu mới."/>}<div className="pagination"><span>Trang 1 / 1</span><div><button disabled><ChevronLeft/></button><button className="active">1</button><button disabled><ChevronRight/></button></div></div></div>
 {modal==='create'&&<Modal title="Đặt chỉ tiêu mới" onClose={()=>setModal(null)} wide><form className="form-grid" onSubmit={create}>{error&&<div className="form-error full">{error}</div>}<label>Mã chỉ tiêu<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="VD: CT-2026-011"/></label><label>Năm kế hoạch<input type="number" required value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></label><label className="full">Tên chỉ tiêu<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Nội dung chỉ tiêu cần đạt"/></label><label className="full">Mô tả<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Căn cứ, phạm vi và yêu cầu thực hiện..."/></label><label>Phòng ban phụ trách<select required value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})}>{deps.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Chu kỳ<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="YEARLY">Hàng năm</option><option value="QUARTERLY">Hàng quý</option><option value="MONTHLY">Hàng tháng</option></select></label><label>Giá trị mục tiêu<input type="number" step="any" required value={form.targetValue} onChange={e=>setForm({...form,targetValue:e.target.value})}/></label><label>Đơn vị tính<input required value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>Trọng số<input type="number" step="0.1" min="0.1" max="10" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></label><label>Hạn hoàn thành<input type="date" required value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="btn secondary" onClick={()=>setModal(null)}>Hủy</button><button className="btn primary">Tạo và giao chỉ tiêu</button></div></form></Modal>}
 {modal==='progress'&&selected&&<Modal title="Cập nhật kết quả thực hiện" onClose={()=>setModal(null)}><form className="form-grid single" onSubmit={updateProgress}><div className="target-preview"><span>{selected.code}</span><strong>{selected.title}</strong><p>Mục tiêu: {selected.targetValue.toLocaleString('vi-VN')} {selected.unit}</p></div>{error&&<div className="form-error full">{error}</div>}<label className="full">Giá trị thực hiện mới<input type="number" step="any" required value={progress.value} onChange={e=>setProgress({...progress,value:+e.target.value})}/></label><label className="full">Ghi chú cập nhật<textarea value={progress.note} onChange={e=>setProgress({...progress,note:e.target.value})} placeholder="Kết quả, nguồn số liệu hoặc vấn đề cần lưu ý..."/></label><div className="modal-actions full"><button type="button" className="btn secondary" onClick={()=>setModal(null)}>Hủy</button><button className="btn primary">Lưu kết quả</button></div></form></Modal>}</>}
